# Generated by Django 4.0.6 on 2022-08-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
