# Generated by Django 4.0.6 on 2022-08-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_pfp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='pfp',
            new_name='image',
        ),
    ]
